name: Rail_312
favicon: null
layout_spectrum: 0.50963
typography_spectrum: 0.32002
title: Rail Industry Insight
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff4400'
    - '#fec000'
    - '#f2f8fe'
    - '#006df2'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
