name: Rail_312
favicon: null
layout_spectrum: 0.2382770013064146
typography_spectrum: 0.8978322148323059
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e11a2d'
    - '#004d6f'
    - '#7999b0'
    - '#fb7a13'
  brandStrength: 0.5
  lightness: 0.5939370314590633
  saturation: 0.22367162047885358
  rhythmicContrast: 0.16565141617320478
purpose: []
